### PR TITLE
Update title to community blog

### PR DESCRIPTION
**Pull request by cosden**
Very minor change to distinguish that this is the blog part of the site.

### CODE REVIEW

**Comment by vsoch** [comment]
You don't think that's a little long?

https://35-186452639-gh.circle-artifacts.com/0/blog/index.html

**Comment by vsoch** [comment]
What about what you referenced in the new about page?

image

**Comment by cosden** [comment]
It looks better short, with US-RSE.  But we need to decide if it's US-RSE, US RSE, or USRSE.  I'm as guilty as anyone in mixing things up.

**Comment by cosden** [comment]
I'll change it to US-RSE for now.

**Comment by vsoch** [comment]
This LGTM.

**Pull request merged**
