### PR TITLE
attempt to add a subset of my blog posts

### PR DESCRIPTION
**Pull request by danielskatz**

### CODE REVIEW

**Comment by vsoch** [comment]
okay, looks like we found your feed and created a folder:

image

The feed is empty (see [here](https://danielskatzblog.wordpress.com/category/RSE/feed)) so the preview doesn't have any new post files. When you add a blog entry to the feed, it will generate in a nightly build and then appear on the site. This LGTM to add, and when you add a post to the category we can watch after the nightly build to make sure wordpress parsing worked okay. The feeds are pretty consistent, however it's still good to check.

**Comment by vsoch** [comment]
If you want to add posts to the feed now, pushing again will rebuild the preview and you can see what they will look like.

**Comment by danielskatz** [comment]
sorry, had added a tag but not a category, now changed to have a category...

**Comment by vsoch** [comment]
We found the posts!

image

I'll do a PR to tweak the generation script to not include variables (see how each filename has a ?). It technically still works okay [see a preview post here](https://23-186452639-gh.circle-artifacts.com/0/blog/2019/dsk/p=1452/index.html) However the file would look prettier without the ? in it!

**Comment by vsoch** [comment]
I also will add an if statement to not print the comma if there isn't a description for the feed (yours doesn't have one)

image

**Comment by danielskatz** [comment]
sure, please go ahead - we can always make more changes later (MVP...)

**Pull request merged**
